# Generated by Django 3.0.6 on 2020-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(blank=True, to='photos.Comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
    ]
